# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://112.124.20.183:3306/BookStore?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: vKQ8G3eC
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 连接池最大连接数
      maximum-pool-size: 10
      # 最小空闲连接数
      minimum-idle: 5
      # 连接超时时间（毫秒）
      connection-timeout: 30000
      # 空闲连接最大存活时间（毫秒）
      idle-timeout: 600000
      # 连接最大存活时间（毫秒）
      max-lifetime: 1800000
      # 自动提交
      auto-commit: true
      # 连接测试查询
      connection-test-query: SELECT 1

  # 添加文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

# 自定义文件上传目录
file:
  upload-dir: ${user.home}/IdeaProjects/BookStore/frontend/public/covers